name: Issues
on:
  issues:
    types: [opened]
jobs:
  print_issue_title:
    runs-on: ubuntu-latest
    name: Print issue title
    steps:
    - run: echo "${{github.event.issue.title}}"
    ## Try creating an issue with a title of:
    ## new issue title" && ls / && echo "
    ## What will happen?